<?php

/*
 *
 *  ____            _        _   __  __ _                  __  __ ____
 * |  _ \ ___   ___| | _____| |_|  \/  (_)_ __   ___      |  \/  |  _ \
 * | |_) / _ \ / __| |/ / _ \ __| |\/| | | '_ \ / _ \_____| |\/| | |_) |
 * |  __/ (_) | (__|   <  __/ |_| |  | | | | | |  __/_____| |  | |  __/
 * |_|   \___/ \___|_|\_\___|\__|_|  |_|_|_| |_|\___|     |_|  |_|_|
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * @author PocketMine Team
 * @link http://www.pocketmine.net/
 *
 *
*/

namespace pocketmine\block;

use pocketmine\item\Item;
use pocketmine\level\Level;
use pocketmine\Player;

#define $this->isActivated() (bool) ($this->meta & 0x08)

class StoneButton extends Lever{
	protected $id = self::STONE_BUTTON;

	public function getAttachSide(){
		$faces = [
			0 => self::SIDE_UP,
			1 => self::SIDE_WEST,
			2 => self::SIDE_EAST,
			3 => self::SIDE_NORTH,
			4 => self::SIDE_SOUTH,
			5 => self::SIDE_DOWN,
		];
		return isset($faces[(int) ($this->meta & 0x07)]) ? $faces[(int) ($this->meta & 0x07)] : self::SIDE_DOWN;
	}

	public function onActivate(Item $item, Player $player = null){
		if($this->isActivated()){
			return false;
		}
		$this->meta |= 0x08;
		$this->getLevel()->setBlock($this, $this);
		$this->getLevel()->scheduleUpdate($this, $this->getDelay());
		$this->getLevel()->updateAround($this->getSide($this->getAttachSide()));
		return true;
	}

	protected function getDelay(){
		return 20;
	}

	public function onUpdate($type){
		parent::onUpdate($type);
		if($type === Level::BLOCK_UPDATE_SCHEDULED){
			$this->meta &= 0x07;
			$this->getLevel()->setBlock($this, $this);
			$this->getLevel()->updateAround($this->getSide($this->getAttachSide()));
		}
	}
	public function place(Item $item, Block $block, Block $target, $face, $fx, $fy, $fz, Player $player = null){
		if($target->isTransparent()){
			return false;
		}
		$chooseMeta = [
			self::SIDE_DOWN => 0,
			self::SIDE_EAST => 1,
			self::SIDE_WEST => 2,
			self::SIDE_SOUTH => 3,
			self::SIDE_NORTH => 4,
			self::SIDE_UP => 5
		];
		$meta = $chooseMeta[$face];
		$this->meta = $meta;
		echo "Face: $face, Meta: $meta\n";
		$this->getLevel()->setBlock($this, $this);
		return true;
	}

	public function onBreak(Item $item){
		$ret = parent::onBreak($item); // TODO: Change the autogenerated stub
		$this->getLevel()->updateAround($this->getSide($this->getAttachSide()));
		return $ret;
	}
}
